name: Build The Application

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        javafx: true
        distribution: 'temurin'
        architecture: x64
        cache: maven


    - name: Install JavaFX JMods
      run: |
        # Define variables for the latest version
        JAVA_FX_JMODS_URL="https://download2.gluonhq.com/openjfx/21.0.4/openjfx-21.0.4_linux-x64_bin-jmods.zip"
        
        # Download and unzip JavaFX JMods
        wget $JAVA_FX_JMODS_URL -O javafx-jmods.zip
        unzip javafx-jmods.zip -d javafx-jmods
        ls 

 


    
  

 

