
#https://github.com/msusdev/end-to-end-github-actions/blob/main/presentations/ci_github_actions.md

name: Build Next.js web application
on: push
jobs:
build-project:
  name: Build Project
  runs-on: ubuntu-latest
  steps:
  - name: Checkout code
    uses: actions/checkout@v4
  - name: build mvn
    run: mvn clean
  - name: Build project assets
    run: mvn install
  - name: stagin
    run: mkdir staging && cp target/*.jar staging
  - name: packaging
    uses: actions/upload-artifact@v4
      with:
        name: MaoPass
        path: ./staging/
 

release-project:
  name: Release Project
  runs-on: ubuntu-latest
  needs: build-project
  steps: 
  - name: Download site content
  uses: actions/download-artifact@v4
  with:
    name: MaoPass
  - name: View content
  run: ls -R
