name: Package JavaFX Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        maven-version: 'latest'  # Use the latest Maven version

    - name: Install JavaFX SDK
      run: |
        wget https://gluonhq.com/download/javafx-sdk-21.0.0-linux.zip
        unzip javafx-sdk-21.0.0-linux.zip -d javafx-sdk
        sudo apt-get update
        sudo apt-get install -y openjdk-21-jdk

    - name: Install JavaFX JMods
      run: |
        wget https://gluonhq.com/download/javafx-jmods-21.0.0.zip
        unzip javafx-jmods-21.0.0.zip -d javafx-jmods

    - name: Build and package application
      run: |
        mvn clean package

    - name: Package with jpackage
      run: |
        appName="YourAppName"
        version="1.0"
        inputDir="target"  # Directory containing the JAR file
        jarFile="MaoPass-1.0.jar"  # Adjust to your app's JAR file name
        outputDir="target/package"
        jmodsDir="${{ github.workspace }}/javafx-jmods/jmods"
        sdkDir="${{ github.workspace }}/javafx-sdk/lib"

        mkdir -p $outputDir
        
        jpackage --input $inputDir --name $appName --version $version --main-jar $jarFile --type deb --dest $outputDir --add-modules javafx.controls,javafx.fxml --module-path $jmodsDir --runtime-image $sdkDir

    - name: Test the packaged application
      run: |
        packagePath="${{ github.workspace }}/target/package/${appName}.deb"
        if [ -f "$packagePath" ]; then
          echo "Debian package created successfully at $packagePath"
          # You can also install and test the package here if needed
        else
          echo "Package not found at path: $packagePath"
          exit 1
        }

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-output
        path: ${{ github.workspace }}/target/package
