name: Build The Application for Ubuntu

on:
  push:
    branches: [ "main" ]


jobs:  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        javafx: true
        distribution: 'temurin'
        architecture: x64
        cache: maven
    - name: Install JavaFX SDK
      run: |
        # Define variables for the latest version
        JAVA_FX_VERSION="21.0.4"  # Update this to the latest version
        JAVA_FX_SDK_URL="https://download2.gluonhq.com/openjfx/21.0.4/openjfx-21.0.4_linux-x64_bin-sdk.zip"
        
        # Download and unzip JavaFX SDK
        wget $JAVA_FX_SDK_URL -O javafx-sdk.zip
        unzip javafx-sdk.zip -d javafx-sdk
        sudo apt-get update
        sudo apt-get install -y openjdk-21-jdk

    - name: Install JavaFX JMods
      run: |
        # Define variables for the latest version
        JAVA_FX_JMODS_URL="https://download2.gluonhq.com/openjfx/21.0.4/openjfx-21.0.4_linux-x64_bin-jmods.zip"
        
        # Download and unzip JavaFX JMods
        wget $JAVA_FX_JMODS_URL -O javafx-jmods.zip
        unzip javafx-jmods.zip -d javafx-jmods

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Clean With maven
      run: mvn clean
    - name: Install dependencies and run tests -Djavafx.platform=gtk -Dtestfx.robot=glass
      run: mvn clean test
    - name: Build with Mvn
      run: mvn install
    # packaging
    - name: copy logo
      run: cp logo.png target/
    - name: copy libs
      run: cp -r lib/  target/
    - name: packaging for debs
      run: cd target/ && jpackage --type deb --input . --dest . --main-jar ./MaoPass-1.0.jar --main-class Main --module-path "../javafx-jmods/javafx-jmods-21.0.4/" --add-modules javafx.controls,javafx.fxml --name MaoPass  --linux-shortcut --install-dir /opt --linux-menu-group Utility  --icon ./logo.png --name "MaoPass"
    - name: stagin
      run: mkdir staging && cp target/*.deb staging
    - name: packaging
      uses: actions/upload-artifact@v4
      with:
        name: MaoPass-1
        path: ./staging/
  release:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact 
        uses: actions/download-artifact@v4
        with:
           name: MaoPass-1

    
  

 

