name: Package JavaFX Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        maven-version: 'latest'  # Use the latest Maven version

    - name: Install JavaFX SDK
      run: |
        Invoke-WebRequest -Uri "https://gluonhq.com/download/javafx-sdk-21.0.0.zip" -OutFile "javafx-sdk.zip"
        Expand-Archive -Path "javafx-sdk.zip" -DestinationPath "javafx-sdk"
        $env:PATH += ";${{ github.workspace }}\javafx-sdk\bin"

    - name: Build and package application
      run: |
        mvn clean package

    - name: Package with jpackage
      run: |
        $env:JAVA_HOME = "C:\Program Files\AdoptOpenJDK\jdk-21"
        $env:PATH += ";$env:JAVA_HOME\bin"
        $appName = "YourAppName"
        $version = "1.0"
        $inputDir = "target\your-app-jar"  # Adjust to your app's jar location
        $outputDir = "target\package"
        
        mkdir $outputDir
        
        jpackage --input $inputDir --name $appName --version $version --main-jar your-app.jar --type exe --dest $outputDir
